//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_client_shared.Resources.Language.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_us {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("api_client_shared.Resources.Language.Data.en_us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CertificateCouldNotFind {
            get {
                return ResourceManager.GetString("CertificateCouldNotFind", resourceCulture);
            }
        }
        
        internal static string CertificateExpiredResult {
            get {
                return ResourceManager.GetString("CertificateExpiredResult", resourceCulture);
            }
        }
        
        internal static string CertificateInvalidChainResult {
            get {
                return ResourceManager.GetString("CertificateInvalidChainResult", resourceCulture);
            }
        }
        
        internal static string CertificateIsNull {
            get {
                return ResourceManager.GetString("CertificateIsNull", resourceCulture);
            }
        }
        
        internal static string CertificateNotActivatedResult {
            get {
                return ResourceManager.GetString("CertificateNotActivatedResult", resourceCulture);
            }
        }
        
        internal static string CertificateNotIssuedToOrganization {
            get {
                return ResourceManager.GetString("CertificateNotIssuedToOrganization", resourceCulture);
            }
        }
        
        internal static string CertificateSelfSignedErrorResult {
            get {
                return ResourceManager.GetString("CertificateSelfSignedErrorResult", resourceCulture);
            }
        }
        
        internal static string CertificateShortDescription {
            get {
                return ResourceManager.GetString("CertificateShortDescription", resourceCulture);
            }
        }
        
        internal static string CertificateUsedExternalResult {
            get {
                return ResourceManager.GetString("CertificateUsedExternalResult", resourceCulture);
            }
        }
        
        internal static string CertificateValidResult {
            get {
                return ResourceManager.GetString("CertificateValidResult", resourceCulture);
            }
        }
        
        internal static string ToleratedPrefixListError {
            get {
                return ResourceManager.GetString("ToleratedPrefixListError", resourceCulture);
            }
        }
        
        internal static string ToleratedXsdIdError {
            get {
                return ResourceManager.GetString("ToleratedXsdIdError", resourceCulture);
            }
        }
    }
}
